queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=verify-common-gc
      - status-success=verify-main-tests (ubuntu-latest)
      - status-success=verify-main-tests (macos-latest)
      - base=master
      - label=automerge-squash
    merge_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=verify-common-gc
      - status-success=verify-main-tests (ubuntu-latest)
      - status-success=verify-main-tests (macos-latest)
      - base=master
      - label=automerge-squash
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}

pull_request_rules:
  - name: Automatic merge (squash)
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=verify-common-gc
      - status-success=verify-main-tests (ubuntu-latest)
      - status-success=verify-main-tests (macos-latest)
      - base=master
      - label=automerge-squash
    actions:
      delete_head_branch: {}
      queue:
  - name: Automatically closing successful trials
    conditions:
      - status-success=verify-common-gc
      - status-success=verify-main-tests (ubuntu-latest)
      - status-success=verify-main-tests (macos-latest)
      - base=master
      - label=autoclose
    actions:
      close:
        message: CI looks good, this dependency bump would not cause problems, hence closing this trial PR.
      delete_head_branch: {}
  - name: Clean up automerge tags
    conditions:
      - closed
    actions:
      label:
        remove:
          - automerge-squash
          - autoclose
  - name: Auto-approve auto-PRs
    conditions:
      - author=pr-automation-bot-public[bot]
      - label=automerge-squash
    actions:
      review:
        type: APPROVE
        message: This bot trusts that bot
  - name: Auto-approve changelog/release PR
    conditions:
      - files=Changelog.md
      - "#files=1"
      - label=automerge-squash
    actions:
      review:
        type: APPROVE
        message: A change to `Changelog.md`? I can handle that!
  - name: Auto-approve dependabot PR
    conditions:
      - -merged
      - -closed
      - files=doc/docusaurus/package-lock.json
      - "#files=1"
    actions:
      review:
        type: APPROVE
        message: A change to `doc/docusaurus/package-lock.json`? I can handle that!
      label:
        add:
          - automerge-squash
