name: build

on:
  push:
    branches:
    - master

jobs:
  # Build on multiple platforms for continuous integration
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-15-intel, ubuntu-26.04-arm, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
    - if: ${{ startsWith(matrix.os, 'ubuntu-') }}
      uses: nixbuild/nixbuild-action@ccd11ee76c26c018e8470835dc2e286a5a024a14 # v27
      with:
        nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
        generate_summary_for: 'workflow'
    - uses: cachix/cachix-action@38b082610b782e7e93e209c35fd730d399dee866 # v17
      with:
        name: ic-hs-test
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nix-build
      shell: bash
      run: |
        cachix watch-exec ic-hs-test -- \
          ${{ github.workspace }}/nixbuild.sh -L \
            .#release.moc \
            .#release.mo-doc \
            .#js.moc \
            .#js.moc_interpreter

        echo "## checks"
        uname -s -m
        moc="$(${{ github.workspace }}/nixbuildcopy.sh .#release.moc)"
        "$moc/bin/moc" --version
        file "$moc/bin/moc"
        ldd "$moc/bin/moc" || true
