name: build

on:
  push:
    branches:
    - master

jobs:
  # Build on multiple platforms for continuous integration
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, ubuntu-24.04-arm, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: ic-hs-test
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nix-build
      run: |
        cachix watch-exec ic-hs-test -- \
          nix build --max-jobs auto -L \
            .#release.moc \
            .#release.mo-doc \
            .#js.moc \
            .#js.moc_interpreter

        echo "## checks"
        uname -s -m
        moc="$(nix build --max-jobs auto .#release.moc --print-out-paths)"
        "$moc/bin/moc" --version
        file "$moc/bin/moc"
        ldd "$moc/bin/moc" || true
