name: "nightly-macos-test"
on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC every day
  workflow_dispatch:  # Allow manual triggering
  
jobs:
  common-tests:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Run Common Tests
        uses: ./.github/actions/test-blueprint
        with:
          os: macos-13
          test-target: common-tests
          test-name: macos-13-common-tests
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  gc-tests:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Run GC Tests
        uses: ./.github/actions/test-blueprint
        with:
          os: macos-13
          test-target: gc-tests
          test-name: macos-13-gc-tests
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  systems-go-tests:
    strategy:
      matrix:
        build_type: [release, debug]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        uses: ./.github/actions/test-blueprint
        with:
          os: macos-13
          test-target: ${{ matrix.build_type }}-systems-go
          test-name: macos-13-${{ matrix.build_type }}-tests
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

  create-issue:
    needs: [common-tests, gc-tests, systems-go-tests]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest # No need to run on macOS-13, the ubuntu runner should be cheaper to run.
    steps:
      - name: Create Issue
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString().split('T')[0];
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Nightly macOS-13 Test Failure (${date})`,
              body: `Nightly tests for macOS-13 failed. Please investigate.\n\nWorkflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              labels: ['macos-13-failure', 'bug']
            }); 