name: release

# We trigger this on all tags and on the `master` branch. The job
# `changelog` will fail for tags that don’t have a
# changelog entry, so that seems good enough.
# For `master` this check is skipped as well as uploads.

on:
  push:
    tags:
    - '*'
    branches:
    - 'master'

jobs:
  # first check that the changelog is in good order and extract the changelog
  # This will fail for non-release tags.
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract changelog
      id: read_changelog
      if: startsWith(github.ref, 'refs/tags/')
      uses: ./.github/actions/extract-changelog
      with:
        version: ${{ github.ref_name }}
    outputs:
      release_body: ${{ steps.read_changelog.outputs.release_body }}

  # Now build the release on both linux and darwin
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, ubuntu-24.04-arm, macos-latest ]
    needs: changelog
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: ic-hs-test
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "nix-build"
      # these are the dependencies listed in release-files. Sorry for the duplication
      run: |
        cachix watch-exec ic-hs-test -- \
          nix build --max-jobs 1 -L \
            .#release.moc \
            .#release.mo-doc \
            .#js.moc \
            .#js.moc_interpreter

        echo "## checks"
        uname -s -m
        moc="$(nix build --max-jobs 1 .#release.moc --print-out-paths)"
        "$moc/bin/moc" --version
        file "$moc/bin/moc"
        ldd "$moc/bin/moc" || true

  # Finally do the upload. Hopefully the previous job has uploaded the
  # build product to the cachix cache, as we cannot build the darwin products on
  # linux
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: 'ubuntu-latest'
    needs: [ changelog, build ]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: ic-hs-test
        # NB: No auth token, we don’t expect to push new stuff here

    - run: nix build --max-jobs 1 .#release-files

    - name: Upload Release Assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: result/*
        file_glob: true
        body: ${{ needs.changelog.outputs.release_body }}
