name: release-pr

on:
  pull_request:
    types: [opened, edited, synchronize, reopened] # Run on PR title change
    branches:
    - master
    paths:
    - Changelog.md

jobs:
  validate-changelog:
    runs-on: ubuntu-latest
    # Only run this job on release PRs. Identify them by the title which is determined by the first commit message as described in the release process.
    if: "${{ startsWith(github.event.pull_request.title, 'chore: Releasing ')}}"
    steps:
    - uses: actions/checkout@v4

    - name: Get the version from the PR title
      id: get_version
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        VERSION=$(echo "$PR_TITLE" | sed -nE 's/^chore: Releasing ([0-9]+\.[0-9]+\.[0-9]+).*$/\1/p')
        echo version=$VERSION >> "$GITHUB_OUTPUT"

    - name: Fail if version is not valid
      run: |
        if [[ -z "${{ steps.get_version.outputs.version }}" ]]; then
          echo "::error::Failed to extract version from PR title. Ensure the title is in the format 'chore: Releasing x.y.z'"
          exit 1
        fi

    - name: Extract changelog for release
      id: read_changelog
      uses: ./.github/actions/extract-changelog
      with:
        version: ${{ steps.get_version.outputs.version }}
