name: Update flake.lock (trial)
on:
  # Manual override, one can start the workflow by running:
  # curl -H "Accept: application/vnd.github.everest-preview+json" \
  #  -H "Authorization: token <your-token-here>" \
  #  --request POST \
  #  --data '{"event_type": "flake-updater-nudge", "client_payload": {}}' \
  #  https://api.github.com/repos/dfinity/motoko/dispatches
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
  repository_dispatch:
    types: flake-updater-nudge
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run every Sunday at midnight
    - cron: '0 0 * * 0'
jobs:
  flake-updater:
    name: 'Update flake.lock'
    timeout-minutes: 2 # if this takes more than 2 minutes then something's wrong
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          branch: "update_flake_lock_action_trial"
          inputs: |
            nixpkgs
            ic-src
            rust-overlay
          pr-title: "chore: weekly `flake.lock` update"
          pr-labels: |
            autoclose
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action
            as defined in [.github/workflows/update-flake-lock-trial.yml]({{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/blob/master/.github/workflows/update-flake-lock-trial.yml)
            and run in: {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }}/attempts/{{ env.GITHUB_RUN_ATTEMPT }}:

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```

            This PR is just to test if the above dependency bumps cause issues.
            If checks fail this PR remains open so we can investigate.
            If all checks succeed this PR is automatically closed.
          token: ${{ secrets.NIV_UPDATER_TOKEN }}
